const Routes = {
	LOADING: "LOADING",

	LOGIN_STACK: "LOGIN_STACK",
	LOGIN_SCREEN: "LOGIN_SCREEN",

	MAIN_APP: "MAIN_APP",
	
	HOME_SCREEN: "HOME_SCREEN",
	PROFILE_SCREEN: 'PROFILE',
	NOTIFICATION_SCREEN:'NOTIFICATIONS'
};

export default Routes;
